name: instagram
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animator: ^2.0.1
  auto_direction: ^0.0.4+1
  cached_network_image: ^2.3.3
  camera: ^0.5.8+11
  cloud_firestore: ^0.12.9+4
  cupertino_icons: ^1.0.0
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  firebase_core: ^0.4.0+9
  firebase_messaging: ^6.0.9
  firebase_storage: ^3.0.6
  flutter_image_compress: ^0.7.0
  geocoder: ^0.2.1
  giphy_get: ^1.0.1
  http: ^0.12.2
  image_cropper: ^1.3.1
  image_downloader: ^0.20.1
  image_picker: ^0.6.7+12
  intl: ^0.16.1
  ionicons: ^0.0.3
  liquid_swipe: ^1.5.0
  location: ^3.0.2
  path_provider: ^1.6.22
  provider: ^4.3.2+2
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  timeago: ^2.0.28
  url_launcher: ^5.7.10
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/images/user_placeholder.jpg
    # - assets/images/instagram_logo.png
    # - assets/images/shutter.png
    # - assets/images/switch_camera.png
    # - assets/images/gallery_button.png
    # - assets/images/verfiriedUserBadge.png
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
